### ISSUE TITLE
Process cancellation

### ISSUE THREAD

**Issue by ruiztulio** [hamed-yousefi/gowl#19]
Hi,

Having the cacellation feature is great, but only works if the task isn't started. I think if we pass the context to the start method (and it behaves as expected) the process itself can be cancelled too.

I know this chance brakes the API, but can be useful in future versions, what do you think @hamed-yousefi ?

Regards.

**Comment by hamed-yousefi** [comment]
Hi @ruiztulio 

Agree with you. The context should be propagated through the primary functions to give us the ability to cancel the process. I have approved and merged your PR. Thank you for your contribution.

Cheers,
